/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ChatParams = {
message: string;
session_id: string;
};

export type SidebarChatParams = {
message: string;
session_id: string;
article_id: number;
};

export type SearchParams = {
search_term: string;
page_num: number;
filter: string;
};

export type SummaryParams = {
prompt: string;
};

export type AutofillParams = {
query: string;
};

